# Generated by Django 6.0.7 on 2026-07-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('juz_count', models.PositiveSmallIntegerField(verbose_name='Juz count')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='Maximum age (years)')),
                ('prize_sar', models.PositiveIntegerField(verbose_name='Prize (SAR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.DateField(verbose_name='Registration opens')),
                ('registration_close', models.DateField(verbose_name='Registration closes')),
                ('preliminaries_date', models.DateField(verbose_name='Preliminaries date')),
                ('finals_date', models.DateField(verbose_name='Finals date')),
                ('venue_en', models.CharField(blank=True, max_length=255, verbose_name='Venue (English)')),
                ('venue_ar', models.CharField(blank=True, max_length=255, verbose_name='Venue (Arabic)')),
                ('about_en', models.TextField(blank=True, verbose_name='About (English)')),
                ('about_ar', models.TextField(blank=True, verbose_name='About (Arabic)')),
            ],
            options={
                'verbose_name': 'Competition Settings',
                'verbose_name_plural': 'Competition Settings',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('nominating_institution', models.CharField(max_length=255, verbose_name='Nominating institution / school')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('id_document', models.FileField(upload_to='documents/%Y/%m/', verbose_name='ID document (National ID / Birth Cert / Passport)')),
                ('passport_photo', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Passport photo (colour)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='Reviewer notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='competition.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
