# Generated by Django 6.0.7 on 2026-07-28 23:04

import apps.competition.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id_document',
            field=models.FileField(storage=apps.competition.storage.IDDocumentStorage(), upload_to=apps.competition.storage.id_document_upload_path, verbose_name='ID document (National ID / Birth Cert / Passport)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='passport_photo',
            field=models.ImageField(storage=apps.competition.storage.PassportPhotoStorage(), upload_to=apps.competition.storage.passport_photo_upload_path, verbose_name='Passport photo (colour)'),
        ),
    ]
