# Generated by Django 6.0.7 on 2026-07-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_aws_s3_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Alternative phone number'),
        ),
        migrations.AddField(
            model_name='registration',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='County (for preliminary)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='current_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Current place of residence'),
        ),
        migrations.AddField(
            model_name='registration',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='National ID / Passport number'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nationality / Residency'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='competition.category', verbose_name='Category'),
        ),
    ]
