# Generated by Django 6.0.7 on 2026-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_add_registration_fields_and_s3_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='finals_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finals end date'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='preliminaries_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Preliminaries end date'),
        ),
        migrations.AlterField(
            model_name='competitionsettings',
            name='finals_date',
            field=models.DateField(verbose_name='Finals start date'),
        ),
        migrations.AlterField(
            model_name='competitionsettings',
            name='preliminaries_date',
            field=models.DateField(verbose_name='Preliminaries start date'),
        ),
    ]
