# Generated by Django 6.0.7 on 2026-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competitionsettings_finals_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='county_registration_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for no limit.', null=True, verbose_name='Per-county registration limit'),
        ),
    ]
