# Generated by Django 6.0.7 on 2026-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competitionsettings_county_registration_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='category_registration_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed registrants per memorisation category. Leave blank for no limit.', null=True, verbose_name='Per-category registration limit'),
        ),
    ]
