# Generated by Django 6.0.7 on 2026-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competitionsettings_category_registration_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, help_text='Username of the admin who performed the action', max_length=150, null=True, verbose_name='User')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(help_text='E.g., Registration, Auth, Settings', max_length=100, verbose_name='Module')),
                ('record_id', models.CharField(blank=True, help_text='ID of the affected record, if applicable', max_length=50, null=True, verbose_name='Record ID')),
                ('record_name', models.CharField(blank=True, help_text='Human-readable name of the affected record', max_length=255, verbose_name='Record Name')),
                ('details', models.JSONField(blank=True, default=dict, help_text='JSON payload of changes (e.g., old vs new values)', verbose_name='Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
