# Generated by Django 6.0.7 on 2026-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='registration',
            name='deletion_reason',
            field=models.TextField(blank=True, verbose_name='Deletion reason / notes'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is deleted / archived'),
        ),
        migrations.AddField(
            model_name='registration',
            name='regret_email_sent',
            field=models.BooleanField(default=False, verbose_name='Regret email sent'),
        ),
        migrations.AddField(
            model_name='registration',
            name='regret_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Regret email sent at'),
        ),
    ]
