# Generated by Django 6.0.7 on 2026-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_registration_deleted_at_registration_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='county_category_limits',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format: {'CountyName': {'category_id': limit}}. Overrides default limits.", verbose_name='Granular County-Category Limits'),
        ),
    ]
