"""
Custom S3 storage backends for competition document uploads.

Files are stored under the registrant's name folder inside the S3 bucket:
  religionattche/<registrant_name>/passport.<ext>
  religionattche/<registrant_name>/identification.<ext>

The <registrant_name> is derived from the Registration.full_name field,
slugified so it is safe to use as an S3 key (no spaces or special characters).
"""
import os
import re
from django.conf import settings

# Only import storages when USE_S3 is enabled; this keeps local dev working
# without boto3 installed.
if getattr(settings, 'USE_S3', False):
    from storages.backends.s3boto3 import S3Boto3Storage
    _S3Base = S3Boto3Storage
else:
    from django.core.files.storage import FileSystemStorage
    _S3Base = FileSystemStorage


def _slugify_name(name: str) -> str:
    """
    Convert a full name into a safe folder name.
    e.g. "John Doe" → "john_doe"
         "أحمد علي"  → "احمد_علي"  (arabic preserved, spaces → underscores)
    """
    # Strip leading/trailing whitespace
    name = name.strip()
    # Replace any sequence of whitespace / slashes with underscore
    name = re.sub(r'[\s/\\]+', '_', name)
    # Remove characters that are problematic in S3 keys (keep letters, digits, -, _, .)
    name = re.sub(r'[^\w.\-]', '', name, flags=re.UNICODE)
    return name or 'unknown'


# ── Upload-to path helpers ────────────────────────────────────────────────────

def passport_photo_upload_path(instance, filename: str) -> str:
    """
    Returns: <registrant_name>/passport.<original_ext>
    e.g.    john_doe/passport.jpg
    """
    ext = os.path.splitext(filename)[1].lower() or '.jpg'
    folder = _slugify_name(instance.full_name)
    return f"{folder}/passport{ext}"


def id_document_upload_path(instance, filename: str) -> str:
    """
    Returns: <registrant_name>/identification.<original_ext>
    e.g.    john_doe/identification.pdf
    """
    ext = os.path.splitext(filename)[1].lower() or '.pdf'
    folder = _slugify_name(instance.full_name)
    return f"{folder}/identification{ext}"


# ── Storage classes ───────────────────────────────────────────────────────────

class PassportPhotoStorage(_S3Base):
    """
    S3 storage for passport photos.
    Enforces public-read ACL so photos can be previewed from the admin panel.
    Falls back to FileSystemStorage in development (USE_S3=False).
    """
    if getattr(settings, 'USE_S3', False):
        # These kwargs are forwarded to S3Boto3Storage
        default_acl = 'private'
        file_overwrite = True            # always replace old photo on re-upload
        custom_domain = None             # use presigned URLs, not public CDN


class IDDocumentStorage(_S3Base):
    """
    S3 storage for ID documents (National ID, Birth Certificate, Passport copy).
    Private ACL — access only via pre-signed URLs generated by the admin.
    Falls back to FileSystemStorage in development (USE_S3=False).
    """
    if getattr(settings, 'USE_S3', False):
        default_acl = 'private'
        file_overwrite = True
        custom_domain = None
